.\"
.\"  Copyright (c) 2014 Masayoshi Wada <developer@andantesoftware.com>
.\"
.\"	@(#)chikubeam.1
.\"
.TH CHIKUBEAM 1 "May 17, 2014"
.SH NAME
chikubeam \- laser beam emitted from nipples. 
.SH SYNOPSIS
.B chikubeam
[
.B \-cfgnswh
]
.SH DESCRIPTION
.B chikubeam
is laser beam emitted from nipples. 
.PP
.TP
.B \-c
change the nipple's color
.TP
.B \-f
the beam is emitted twice as fast as normal
.TP
.B \-r
round mode
.TP
.B \-n NUM
the beam is emitted NUM times
.TP
.B \-s
change the nipple's shape to 'star'
.TP
.B \-w
change the beam's appearance to '~'
.TP
.B \-h
display help and exit
.PP
.SH GITHUB REPO
\fIhttps://github.com/masawada/chikubeam\fR
.SH AUTHOR
Masayoshi Wada <developer@andantesoftware.com>
.SH BUGS
See Issues on GitHub: \fIhttps://github.com/masawada/chikubeam/issues\fR
